<?php
/**
 * Signing secret for Glide image URLs.
 *
 * This file must stay free of WordPress dependencies: media.php loads it
 * without booting WordPress. The secret lives in wp-content/noon-image-secret.php
 * (generated on activation) so it is unique per site. Defining
 * NOON_IMAGE_SECRET in wp-config.php is also supported on the WordPress side,
 * but media.php can only see the generated file, so prefer the file.
 *
 * @package Noon_Focal_Retina_Image_Generator
 */

if ( ! defined( 'NOON_FOCAL_CONTENT_DIR' ) ) {
	// wp-content, derived from this file's location so it works without WordPress.
	define( 'NOON_FOCAL_CONTENT_DIR', dirname( __DIR__, 3 ) );
}

if ( ! defined( 'NOON_FOCAL_CACHE_DIR' ) ) {
	define( 'NOON_FOCAL_CACHE_DIR', NOON_FOCAL_CONTENT_DIR . '/cache/noon-images' );
}

if ( ! defined( 'NOON_FOCAL_UPLOADS_DIR' ) ) {
	define( 'NOON_FOCAL_UPLOADS_DIR', NOON_FOCAL_CONTENT_DIR . '/uploads' );
}

if ( ! function_exists( 'noon_focal_webp_supported' ) ) {

	function noon_focal_webp_supported() {
		return function_exists( 'imagewebp' ) || class_exists( 'Imagick' );
	}

	/**
	 * Whether Glide can decode the file. SVG and other non-raster uploads pass
	 * wp_attachment_is_image() (with plugins such as Safe SVG) but GD cannot
	 * read them, so they are served untouched.
	 *
	 * @param string $file Path or URL of the upload.
	 */
	function noon_focal_is_raster( $file ) {
		$extension = strtolower( pathinfo( (string) $file, PATHINFO_EXTENSION ) );
		return in_array( $extension, array( 'jpg', 'jpeg', 'jpe', 'png', 'gif', 'webp', 'bmp' ), true );
	}

	/**
	 * Glide parameters applied to every rendition of a file. Shared by media.php
	 * and the cache warmer so both produce identical cache keys.
	 *
	 * @param string $file Path of the upload, used for its extension.
	 * @param bool   $webp Whether to output WebP (client accepts it and PHP can encode it).
	 */
	function noon_focal_default_params( $file, $webp ) {

		$extension = strtolower( pathinfo( $file, PATHINFO_EXTENSION ) );

		// PNG/GIF keep their format (transparency, animation); everything else becomes JPEG.
		$params = array(
			'q'  => 80,
			'fm' => in_array( $extension, array( 'png', 'gif' ), true ) ? $extension : 'jpg',
		);

		if ( $webp && noon_focal_webp_supported() && 'gif' !== $extension ) {
			$params['fm'] = 'webp';
		}

		return $params;

	}

}

if ( ! function_exists( 'noon_focal_secret_file' ) ) {

	function noon_focal_secret_file() {
		return NOON_FOCAL_CONTENT_DIR . '/noon-image-secret.php';
	}

	/**
	 * Create the per-site secret file if it does not exist yet.
	 * Returns true when a secret is available afterwards.
	 */
	function noon_focal_ensure_secret() {

		if ( defined( 'NOON_IMAGE_SECRET' ) ) {
			return true;
		}

		$file = noon_focal_secret_file();

		if ( ! file_exists( $file ) ) {

			$secret   = bin2hex( random_bytes( 32 ) );
			$contents = "<?php\n// Generated by Focal Retina Image Generator. Do not commit or share.\n"
				. "define( 'NOON_IMAGE_SECRET', '" . $secret . "' );\n";

			if ( false === @file_put_contents( $file, $contents, LOCK_EX ) ) {
				return false;
			}

			@chmod( $file, 0600 );

		}

		require_once $file;

		return defined( 'NOON_IMAGE_SECRET' );

	}

}

if ( ! defined( 'NOON_IMAGE_SECRET' ) && file_exists( noon_focal_secret_file() ) ) {
	require_once noon_focal_secret_file();
}
